# Generated by Django 5.2.4 on 2025-07-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_upload',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
